[versions]
geantyref = "2.0.0"
jspecify = "1.0.0"
jupiter-api = "5.11.2"
jupiter-engine = "5.11.2"
jupiter-params = "5.11.2"

[libraries]
geantyref = { module = "io.leangen.geantyref:geantyref", version.ref = "geantyref" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter-api" }
jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter-engine" }
jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter-params" }
